# Generated by Django 3.2.5 on 2021-09-28 06:19

from django.db import migrations, models
import django.db.models.deletion
import toris.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Country')),
                ('un_continental', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('mobile', models.CharField(max_length=13, null=True, verbose_name='Mobile')),
                ('gst_no', models.CharField(max_length=15, null=True, verbose_name='GSTNo')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('designation', models.CharField(max_length=30, unique=True, verbose_name='Designation')),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('code', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='District_name')),
                ('headquarters', models.CharField(max_length=40, verbose_name='Headquarters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('mname', models.CharField(max_length=100, null=True, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('mobile1', models.CharField(max_length=13, null=True, verbose_name='Mobile1')),
                ('mobile2', models.CharField(max_length=13, null=True, verbose_name='Mobile2')),
                ('aadhhar_no', models.CharField(max_length=16, null=True, verbose_name='Aadhhar')),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to=toris.models.upload_to_folder, verbose_name='Image')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='toris.designation', verbose_name='Designation')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Plant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('product_code', models.IntegerField(unique=True, verbose_name='Product Code')),
                ('color_marking_on_bobin', models.CharField(default=None, max_length=200, null=True, verbose_name='Color marking on bobin')),
                ('tape_color', models.CharField(default=None, max_length=100, null=True, verbose_name='Tape Color')),
                ('denier', models.IntegerField(default=None, null=True, verbose_name='Denier')),
                ('gramage', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Gramage')),
                ('tape_width', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Tape Width in mm')),
                ('cutter_spacing', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Cutter Spacing in mm')),
                ('stock_of_bobin', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Bobin Stock')),
                ('streanth_per_tape_in_kg', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Strength per tape in kg')),
                ('elongation_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Elongation %')),
                ('tenacity', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Tanacity')),
                ('pp_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='PP %')),
                ('filler_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Filler %')),
                ('shiner_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Shiner %')),
                ('color_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Color %')),
                ('tpt_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='TPT %')),
                ('uv_percent', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='UV %')),
                ('color_name', models.CharField(default=None, max_length=50, null=True, verbose_name='Color name')),
            ],
            options={
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateField(verbose_name='Production Date')),
                ('shift', models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='DAY', max_length=5, verbose_name='Shift')),
                ('no_of_winderman', models.IntegerField()),
                ('end_reading', models.IntegerField(verbose_name='End Reading')),
                ('start_reading', models.IntegerField(verbose_name='Start Reading')),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wastage')),
                ('operator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_name', to='toris.employee', verbose_name='Employee Name')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='toris.plant')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_productions', to='toris.product', verbose_name='Product Code')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('order_date', models.DateField(null=True, verbose_name='date order')),
                ('order_qty', models.IntegerField(null=True, verbose_name='Order Quantity in kg')),
                ('pi_number', models.CharField(max_length=200, null=True, verbose_name='PI Number')),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='toris.customer', verbose_name='Customer Name')),
                ('product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='toris.product', verbose_name='Product Code')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='toris.state', verbose_name='States'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.district'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.state'),
        ),
    ]
