# Generated by Django 3.2.5 on 2021-08-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='operator_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operatorname', to='toris.operator', verbose_name='Operator Name'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='toris.plant'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcode', to='toris.product', verbose_name='Product Code'),
        ),
    ]
