# Generated by Django 3.2.5 on 2021-08-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0002_auto_20210822_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='toris.product', verbose_name='Product Code'),
        ),
    ]
