# Generated by Django 3.2.5 on 2021-07-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yahoo_symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('nse_symbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('prev_close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('delivary_volume', models.IntegerField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
            ],
        ),
    ]
