# Generated by Django 3.2.5 on 2021-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nse_symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stockapp_stock',
        ),
    ]
