# Generated by Django 3.2.5 on 2021-07-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210715_1214'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
