# Generated by Django 3.2.5 on 2021-07-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_stock_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
