# Generated by Django 3.2.5 on 2021-08-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Operator Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=3, verbose_name='Plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('product_code', models.IntegerField(verbose_name='Product Code')),
                ('color_marking_on_bobin', models.CharField(max_length=200, verbose_name='Color marking on bobin')),
                ('tape_color', models.CharField(max_length=100, verbose_name='Tape Color')),
                ('denier', models.IntegerField(verbose_name='Denier')),
                ('gramage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramage')),
                ('tape_width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tape Width in mm')),
                ('cutter_spacing', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cutter Spacing in mm')),
                ('stock_of_bobin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bobin Stock')),
                ('streanth_per_tape_in_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Strength per tape in kg')),
                ('elongation_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Elongation %')),
                ('tanacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tanacity')),
                ('pp_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PP %')),
                ('filler_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Filler %')),
                ('shiner_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shiner %')),
                ('color_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Color %')),
                ('tpt_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TPT %')),
                ('uv_percent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UV %')),
                ('color_name', models.CharField(max_length=50, verbose_name='Color name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateField(verbose_name='Production Date')),
                ('shift', models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='DAY', max_length=20, verbose_name='Shift')),
                ('no_of_winderman', models.IntegerField()),
                ('end_reading', models.IntegerField(verbose_name='End Reading')),
                ('start_reading', models.IntegerField(verbose_name='Start Reading')),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wastage')),
                ('operator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.operator', verbose_name='Operator Name')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.plant')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toris.product', verbose_name='Product Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('order_date', models.DateField(verbose_name='date order')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('order_qty', models.IntegerField(verbose_name='Order Quantity in kg')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toris.product', verbose_name='Product Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
