# Generated by Django 3.2.5 on 2021-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='date',
            field=models.DateField(),
        ),
    ]
