# Generated by Django 3.2.5 on 2021-08-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pi_number',
            field=models.CharField(default=1, max_length=200, verbose_name='PI Number'),
            preserve_default=False,
        ),
    ]
