# Generated by Django 3.2.5 on 2021-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='shift',
            field=models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='DAY', max_length=20, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_marking_on_bobin',
            field=models.CharField(max_length=200, verbose_name='Color marking on bobin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name',
            field=models.CharField(max_length=50, verbose_name='Color name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Color %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cutter_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cutter Spacing mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filler_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Filler %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pp_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PP %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(max_length=12, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='req_elongation_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Elongation %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='req_gramage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='req_streanth_per_tape_in_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Strength per tape in kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='req_tape_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tape Width mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shiner_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shiner %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_of_bobin',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bobin Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='streanth',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tanacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tanacity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tape_color',
            field=models.CharField(max_length=100, verbose_name='Tape Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tpt_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TPT %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uv_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UV %'),
        ),
    ]
