# Generated by Django 3.2.5 on 2021-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0002_order_pi_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='shift',
            field=models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='DAY', max_length=5, verbose_name='Shift'),
        ),
    ]
