# Generated by Django 3.2.5 on 2021-08-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0002_auto_20210802_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='date',
            field=models.DateField(verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='end_reading',
            field=models.IntegerField(verbose_name='End Reading'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='operator_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toris.operator', verbose_name='Operator Name'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toris.product', verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='start_reading',
            field=models.IntegerField(verbose_name='Start Reading'),
        ),
        migrations.AlterField(
            model_name='plantproduction',
            name='wastage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wastage'),
        ),
    ]
