# Generated by Django 3.2.5 on 2021-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0002_remove_plantproduction_wastage_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
