# Generated by Django 3.2.5 on 2021-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0003_order_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduction',
            name='shift',
            field=models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT')], default='DAY', max_length=20),
        ),
    ]
