# Generated by Django 3.2.5 on 2021-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0003_auto_20210802_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(verbose_name='Product Code'),
        ),
    ]
