# Generated by Django 3.2.5 on 2021-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0005_alter_product_req_denier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cutter_spacing',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cutter Spacing in mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='req_tape_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tape Width in mm'),
        ),
    ]
