# Generated by Django 3.2.5 on 2021-08-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toris', '0006_auto_20210802_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Operator Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_qty',
            field=models.IntegerField(verbose_name='Order Quantity in kg'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toris.product', verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=3, verbose_name='Plant'),
        ),
    ]
