# Generated by Django 4.0.1 on 2022-03-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('sector', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nse_symbol', models.CharField(max_length=50, null=True, unique=True)),
                ('moneycontrol_symbol', models.CharField(max_length=50, null=True, unique=True)),
                ('yahoo_symbol', models.CharField(max_length=50, null=True, unique=True)),
                ('scrip_code', models.CharField(max_length=10, null=True, unique=True)),
                ('is_portfolio_stock', models.BooleanField(default=False)),
                ('m_cap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.marketcap')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField()),
                ('side', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trade_num', models.BigIntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockmap')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='NSEHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prv_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('deliverable_volume', models.BigIntegerField()),
                ('deliverble_per', models.DecimalField(decimal_places=2, max_digits=12)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockmap')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='NSEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dayhigh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daylow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lastprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previousclose', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pchange', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearhigh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearlow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totaltradedvolume', models.IntegerField()),
                ('perchange365d', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('perchange30d', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('dayendclose', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('corporate_action', models.CharField(max_length=100, null=True)),
                ('x_date', models.DateTimeField(null=True)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockmap')),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='NSEBhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prv_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('isin', models.CharField(max_length=14, null=True)),
                ('symbol', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockmap')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockmap')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
