# Generated by Django 4.0.1 on 2022-03-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField()),
                ('invoice_json', models.TextField()),
                ('total_amt_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igstcheck', models.BooleanField()),
                ('eway_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('invoice_number',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Litter', 'Litter'), ('Meter', 'Meter')], max_length=50)),
                ('rate_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invoice_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('invoice_json', models.TextField()),
                ('total_amt_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igstcheck', models.BooleanField()),
                ('eway_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lr_number', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('business_title', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, max_length=400, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('alert_level', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('purchaseinvoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseinvoiceitem', to='inventory.purchaseinvoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('purchaseinvoice',),
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceitem', to='inventory.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('invoice',),
            },
        ),
    ]
