# Generated by Django 4.0.1 on 2022-03-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='igst_igst',
            new_name='total_amt_cgst',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_cgst',
            new_name='total_amt_igst',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_sgst',
            new_name='total_amt_sgst',
        ),
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='igst_igst',
            new_name='total_amt_cgst',
        ),
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='total_cgst',
            new_name='total_amt_igst',
        ),
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='total_sgst',
            new_name='total_amt_sgst',
        ),
    ]
